"""Carousel Editor prompts: script -> shot list (N slides, 4-6, LLM-decided
per story density) -> shared background creative-direction -> per-slide
creative-direction. Mirrors reel_editor's script->shotlist split, but for
stills.

Visual consistency across slides comes from generation mechanics, not just
prompt wording: one shared background image is generated once, then each
slide is produced by editing that same background (image_provider.py's
generate_full_design with reference_image=<shared background>), adding only
that slide's own headline/body_text. See carousel_editor/graph.py.

No Pillow-drawn content text, same "no programmatic content text" policy as
posters/reels - each slide's headline/body_text is rendered by the image
model itself, verbatim, or not shown at all.
"""

SYSTEM_PROMPT_SHOTLIST = """You are the shot-listing step of a Carousel Editor agent. You're given a \
narrative script for a multi-slide picture carousel (a set of still images posted together, swiped \
through in order, telling one complete story) and the source article's actual content. Break the \
script into an ordered sequence of slides - one clear beat/idea per slide - choosing the slide count \
yourself based on how much the story actually needs: never fewer than 4, never more than 6. A simple, \
single-point story should use 4; a genuinely dense story with several distinct beats can use 5 or 6. \
Don't pad a simple story to hit 6, and don't compress a dense one down to 4.

Each slide needs:
- "headline": a short, punchy line (a handful of words, not a sentence) - the single most important \
  thing this slide says. Every slide's headline should read as part of one continuous story when swiped \
  through in order - slide 1 hooks the reader in, the last slide resolves/lands the point, and each one \
  in between advances the story one step rather than restating the same idea.
- "body_text": one supporting sentence or short line of context for this slide's headline - can be \
  empty string if the headline alone carries the beat fully.

NEVER invent a fact, quote, or number that isn't in the article - state real ones exactly as given, \
and lean on framing/narrative language rather than invented specifics for anything not actually in the \
source material.

Write every slide's "headline" and "body_text" in the target language given to you below - match it \
exactly, do not translate to English or default to it, even if the script or article content you're \
given happens to be in a different language. This is the actual text the image model will render onto \
each slide, so it's the one thing here that must end up in the right language, not just the article's \
own framing.

Keep slides in narrative order - slide 1 opens the story, the last slide resolves it.

Respond with ONLY a JSON object, no markdown fence, no commentary:
{
  "slides": [
    {"headline": "...", "body_text": "..."}
  ]
}"""


def build_shotlist_user_prompt(
    carousel_script: str, article_title: str, article_text: str, language_name: str
) -> str:
    truncated = article_text[:6000]
    return f"""Script:
{carousel_script}

Article title: {article_title}
Article content (for exact facts/quotes/numbers, don't invent anything beyond this):
{truncated}

Target language for every slide's headline/body_text: {language_name}

Return the JSON object now. Between 4 and 6 slides, whatever the story actually needs."""


# Shared background: no text at all, just one consistent scene/style that
# every slide will be generated FROM (via reference-image editing) - the
# actual mechanism that makes slides look consistent with each other, not
# just prompt wording alone.
SYSTEM_PROMPT_BACKGROUND = """You are the creative-direction step of a Carousel Editor agent. You're \
given one article that's being turned into a multi-slide picture carousel (several still images swiped \
through in order, telling one complete story) and your job is to write a vivid, SPECIFIC prompt for an \
image generation model that will produce ONE shared background image - no text, no words, no numbers \
anywhere in it. This single image will be reused as the visual foundation for every slide in the \
carousel (each slide is generated by editing a copy of this exact background to add its own text), so \
it must work as a backdrop for several different pieces of short text across its slides, not just one.

Ground the scene in the actual story - a concrete setting, object, or visual metaphor drawn from the \
article's real content, not a generic abstract concept. Pick ONE coherent art style, color palette, \
mood, and lighting treatment for the whole carousel - this is the single biggest lever for making all \
the slides feel like one consistent set rather than unrelated images stitched together. Vary these \
creative choices from carousel to carousel based on what actually fits each story - two carousels on \
different articles should look like two different pieces, not the same backdrop style reused.

Hard requirements for the prompt you write:
- Absolutely NO text, words, numbers, or lettering of any kind anywhere in the image - this is a pure \
  background, every slide's own text gets added afterward in a separate step.
- The composition MUST reserve exactly ONE fixed, clearly bounded text zone covering roughly the TOP \
  30-35% of the frame - deliberately plain, low-detail, and high-contrast-friendly there (a simple \
  solid/gradient panel, soft blur, or open sky/wall, not the scene's busiest elements). This is not \
  just "some breathing room" - it must read as a distinct, calm band, clearly separate from the artwork \
  below it, because every slide's headline and body text will be placed inside this exact same zone and \
  nowhere else. Put the scene's actual detail/artwork in the remaining ~65-70% of the frame below it.
- No rendering of real named individuals' likenesses.
- Leave the bottom ~10% of the frame visually calm/low-detail too - a brand strip gets added there \
  afterward and shouldn't fight with busy art.

Respond with ONLY the image generation prompt itself (3-5 sentences), no preamble, no quotes around \
your whole answer, no markdown, nothing else."""


def build_user_prompt_background(article_title: str, article_text: str, carousel_script: str) -> str:
    truncated = article_text[:4000]
    return f"""Carousel story/script:
{carousel_script}

Article title: {article_title}
Article context:
{truncated}

Write the shared background image generation prompt now. Remember: no text, no words, no numbers \
anywhere in it - just the background art/style every slide will share."""


# Per-slide: the shared background is passed as a reference image
# (image_provider.py's generate_full_design), so this prompt only ever asks
# for THIS slide's own text to be added on top of it - never a new scene.
SYSTEM_PROMPT_SLIDE = """You are the creative-direction step of a Carousel Editor agent, writing the \
prompt for ONE slide of a multi-slide picture carousel. A shared background image (attached separately \
as a reference image) has already been designed for the whole carousel - your job is to write a prompt \
for an image-editing-capable model that keeps that background essentially as-is and composes this \
slide's own headline and body text into it as real, styled typography.

Hard requirements for the prompt you write:
- Instruct the model to preserve the reference background image as-is - the scene, style, color \
  palette, lighting, AND its composition/framing/crop - not to repaint, restyle, regenerate, re-crop, \
  rescale, or shift it. It is the shared visual foundation for every slide in this carousel, being \
  reused, not a reference sketch for a new image.
- It MUST instruct the model to place BOTH the headline and body text entirely within the plain text \
  zone that already exists in the top ~30-35% of the reference background - never overlapping, \
  extending into, or sitting on top of the artwork/scene below that zone. This exact placement (same \
  region, same position) is what every other slide in this carousel also uses, so the whole set reads \
  as one consistent template - do not improvise a different position for this slide.
- It MUST instruct the model to render the exact headline and body text given to you below, verbatim \
  and unaltered - not paraphrased, shortened, or reworded - quoting them directly in your prompt, with \
  real typographic hierarchy (the headline reads as more important than the body text) within that zone.
- It MUST also instruct the model to render a small sequence indicator in the top-right corner of that \
  same text zone - the slide's position given to you below (e.g. "2/6"), styled small and secondary, \
  much smaller than the headline, so it reads as a page marker rather than content. If this is NOT the \
  final slide, the indicator MUST also include a right-pointing arrow glyph or arrow shape immediately \
  after the number, signalling more slides follow when swiped. If this IS the final slide, show only \
  the number, no arrow. Use the same small style/position for this indicator on every slide, so it \
  reads as one consistent page-counter across the whole carousel.
- High contrast between the text and whatever's behind it.
- No other invented text, words, or numbers anywhere else in the image besides that headline, body \
  text, and the sequence indicator.
- No rendering of real named individuals' likenesses as new imagery beyond what the background already \
  has.
- Leave the bottom ~10% of the frame visually calm/low-detail - a brand strip gets added there \
  afterward and shouldn't fight with busy art.

Respond with ONLY the image generation prompt itself (3-5 sentences), no preamble, no quotes around \
your whole answer, no markdown, nothing else."""


def build_user_prompt_slide(
    headline: str, body_text: str, slide_number: int, slide_count: int, article_title: str
) -> str:
    is_last = slide_number == slide_count
    sequence_note = (
        f'Sequence indicator to render: "{slide_number}/{slide_count}", no arrow (this is the final slide).'
        if is_last
        else f'Sequence indicator to render: "{slide_number}/{slide_count}" followed by a right-pointing arrow.'
    )
    return f"""A shared background image is attached separately as your visual reference.

{sequence_note}

This is slide {slide_number} of {slide_count} in the carousel.
Headline to render (verbatim): "{headline}"
Body text to render (verbatim, may be empty): "{body_text}"

Article title (for grounding only, not to be quoted): {article_title}

Write the image generation prompt now. Remember to instruct the model to preserve the reference \
background as-is, keep the headline, body text, and sequence indicator confined to the reserved top \
text zone only (never over the artwork), and render the headline/body text verbatim as styled \
typography with the small sequence indicator in that zone's top-right corner."""
