"""whatsapp integration fields

Revision ID: 45c2724db98e
Revises: 4b32de301003
Create Date: 2026-09-04 20:46:14.518395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c2724db98e'
down_revision: Union[str, None] = '4b32de301003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_kit', sa.Column('whatsapp_recipient', sa.String(length=100), nullable=True))
    op.add_column('media_assets', sa.Column('public_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'media_assets', ['public_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_assets', type_='unique')
    op.drop_column('media_assets', 'public_token')
    op.drop_column('brand_kit', 'whatsapp_recipient')
    # ### end Alembic commands ###
