"""link niche to brand kit

Revision ID: 4b32de301003
Revises: a27c26c1e5fb
Create Date: 2026-09-04 20:30:32.468003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b32de301003'
down_revision: Union[str, None] = 'a27c26c1e5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_kit', sa.Column('industry', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('niche_config', sa.Column('brand_kit_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'niche_config', 'brand_kit', ['brand_kit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'niche_config', type_='foreignkey')
    op.drop_column('niche_config', 'brand_kit_id')
    op.drop_column('brand_kit', 'industry')
    # ### end Alembic commands ###
