"""reel templates

Revision ID: 88d80bbc19fe
Revises: 408212058841
Create Date: 2026-09-05 02:03:48.988245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d80bbc19fe'
down_revision: Union[str, None] = '408212058841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('reel_template', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'reel_template')
    # ### end Alembic commands ###
