"""phase 1b: per-article content items, drop per-email triage fields

Revision ID: 9a3c64d5c9e0
Revises: ec156060ecf4
Create Date: 2026-09-04 16:08:47.155253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3c64d5c9e0'
down_revision: Union[str, None] = 'ec156060ecf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='' on the NOT NULL text columns: both tables already
    # have rows from before this migration (pre-refactor, email-level data),
    # so a bare NOT NULL add_column would fail with no default to backfill.
    op.add_column(
        'content_items',
        sa.Column('article_title', sa.String(length=500), nullable=False, server_default=''),
    )
    op.add_column('content_items', sa.Column('article_url', sa.String(length=2000), nullable=True))
    op.add_column(
        'content_items', sa.Column('article_summary', sa.Text(), nullable=False, server_default='')
    )
    op.add_column('content_items', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('content_items', sa.Column('priority_rationale', sa.Text(), nullable=True))
    op.add_column('content_items', sa.Column('article_full_text', sa.Text(), nullable=True))
    op.add_column(
        'ingested_emails', sa.Column('body_with_links', sa.Text(), nullable=False, server_default='')
    )
    op.add_column('ingested_emails', sa.Column('articles_found', sa.Integer(), nullable=True))
    op.drop_column('ingested_emails', 'priority_score')
    op.drop_column('ingested_emails', 'priority_rationale')
    op.drop_column('ingested_emails', 'suitable_for_social')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingested_emails', sa.Column('suitable_for_social', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ingested_emails', sa.Column('priority_rationale', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ingested_emails', sa.Column('priority_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('ingested_emails', 'articles_found')
    op.drop_column('ingested_emails', 'body_with_links')
    op.drop_column('content_items', 'article_full_text')
    op.drop_column('content_items', 'priority_rationale')
    op.drop_column('content_items', 'priority_score')
    op.drop_column('content_items', 'article_summary')
    op.drop_column('content_items', 'article_url')
    op.drop_column('content_items', 'article_title')
    # ### end Alembic commands ###
