"""poster templates

Revision ID: a27c26c1e5fb
Revises: df484bddf1f7
Create Date: 2026-09-04 19:44:29.201170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a27c26c1e5fb'
down_revision: Union[str, None] = 'df484bddf1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('poster_template', sa.String(length=30), nullable=True))
    op.add_column(
        'content_items',
        sa.Column('poster_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'poster_content')
    op.drop_column('content_items', 'poster_template')
    # ### end Alembic commands ###
