"""brand kit: identity/handles instead of colors, fixed font dropdown

Revision ID: ae99fb1da090
Revises: c83c160568eb
Create Date: 2026-09-04 16:55:04.152040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae99fb1da090'
down_revision: Union[str, None] = 'c83c160568eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default: brand_kit already has a row (Phase 0), so a bare NOT
    # NULL add_column has nothing to backfill it with.
    op.add_column(
        'brand_kit', sa.Column('brand_name', sa.String(length=200), nullable=False, server_default='')
    )
    op.add_column('brand_kit', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.add_column(
        'brand_kit',
        sa.Column(
            'social_handles', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'
        ),
    )
    op.add_column(
        'brand_kit', sa.Column('font_choice', sa.String(length=50), nullable=False, server_default='inter')
    )
    op.drop_column('brand_kit', 'colors')
    op.drop_column('brand_kit', 'fonts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_kit', sa.Column('fonts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('brand_kit', sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('brand_kit', 'font_choice')
    op.drop_column('brand_kit', 'social_handles')
    op.drop_column('brand_kit', 'website_url')
    op.drop_column('brand_kit', 'brand_name')
    # ### end Alembic commands ###
