"""phase 2: content writer + graphic designer fields, media_assets

Revision ID: c83c160568eb
Revises: 9a3c64d5c9e0
Create Date: 2026-09-04 16:41:52.029016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c83c160568eb'
down_revision: Union[str, None] = '9a3c64d5c9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('storage_uri', sa.String(length=1000), nullable=False),
    sa.Column('generation_model', sa.String(length=150), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('content_items', sa.Column('copy_text', sa.Text(), nullable=True))
    # server_default: content_items already has rows from Phase 1, so a bare
    # NOT NULL add_column has nothing to backfill them with.
    op.add_column(
        'content_items',
        sa.Column(
            'hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'
        ),
    )
    op.add_column('content_items', sa.Column('poster_headline', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'poster_headline')
    op.drop_column('content_items', 'hashtags')
    op.drop_column('content_items', 'copy_text')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
