"""phase 3: reel editor fields, is_processing, last_error

Revision ID: df484bddf1f7
Revises: ae99fb1da090
Create Date: 2026-09-04 17:26:28.627719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df484bddf1f7'
down_revision: Union[str, None] = 'ae99fb1da090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default on the two NOT NULL columns: content_items already has
    # rows from earlier phases, so a bare NOT NULL add_column has nothing to
    # backfill them with.
    op.add_column('content_items', sa.Column('reel_script', sa.Text(), nullable=True))
    op.add_column('content_items', sa.Column('character_description', sa.Text(), nullable=True))
    op.add_column(
        'content_items',
        sa.Column(
            'reel_scenes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'
        ),
    )
    op.add_column('content_items', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column(
        'content_items', sa.Column('is_processing', sa.Boolean(), nullable=False, server_default='false')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'is_processing')
    op.drop_column('content_items', 'last_error')
    op.drop_column('content_items', 'reel_scenes')
    op.drop_column('content_items', 'character_description')
    op.drop_column('content_items', 'reel_script')
    # ### end Alembic commands ###
