"""phase 1: content_items, ingested_emails, oauth_credentials, sync_state, content_item_versions

Revision ID: ec156060ecf4
Revises: ce089610bf3e
Create Date: 2026-09-04 15:12:00.158382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec156060ecf4'
down_revision: Union[str, None] = 'ce089610bf3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingested_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=100), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('priority_rationale', sa.Text(), nullable=True),
    sa.Column('suitable_for_social', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id')
    )
    op.create_table('oauth_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('sync_state',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('content_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_email_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_email_id'], ['ingested_emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_item_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=150), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'llm_call_log', 'content_items', ['content_item_id'], ['id'])
    op.add_column('niche_config', sa.Column('rationale', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('niche_config', 'rationale')
    op.drop_constraint(None, 'llm_call_log', type_='foreignkey')
    op.drop_table('content_item_versions')
    op.drop_table('content_items')
    op.drop_table('sync_state')
    op.drop_table('oauth_credentials')
    op.drop_table('ingested_emails')
    # ### end Alembic commands ###
